# theme: jekyll-theme-hacker
theme: jekyll-shell-theme
title: [trevcan's blog static site]
description: ["no, i don't serve cookies. Please [make your own](https://i.imgur.com/ksl2b1b.jpeg)"]

include:
 - "www/**/*.md"
 - "*.md"

plugins:
  - jekyll-remote-theme 
  - jemoji
  - jekyll_feed


# remote_theme: tareqdandachi/jekyll-shell-theme

sass:
  style: compressed
    #  - jekyll-feed

