title: Trevcan's blog
description: "Trevcan's wannabe hacker blog idk."
author:
  name: "Trevcan Hector Canizales"
  email: "hector [dot] canizales `at` tuta [dot] io"
  url: "https://trevcan.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 6
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: "/www/*.md"
        type: "posts"
    values:
      layout: "post"

include:
   - "www/**/*.md"
   - "*.md"
   - "www/*.md"



future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Hector Canizales"
year : "2021~∞"
